### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by JannikZed** [pavlovml/match#28]
As there are several opened issues without any answers along with open pull requests I wanted to ask, if this project is still maintained or not.

**Comment by kern** [comment]
Hey @JannikZed, I'm pretty confident the code works as-is — most issues seem to be related to (mis-)configurations of elasticsearch which are out of scope of this project. Let me know if you run into issues.

**Comment by JannikZed** [comment]
Hi there,
nice to hear that! I just stumbled upon the first problem. Elasticsearch client in your container is in a really old version `elasticsearch (2.3.0)`. Talking with our elastic version 6 cluster is impossible. Do consider enabling a newer version? I can create an pull request really fast using `'elasticsearch>=6.0.0,<7.0.0'`

**Comment by kern** [comment]
That would be great! Happy to merge :)

Sent via Superhuman iOS ( https://sprh.mn/?vip=alex@kern.io )

**Comment by JannikZed** [comment]
cool, I placed it in - could you take a look?

**Comment by kern** [comment]
merged, thanks @JannikZed!

**Comment by JannikZed** [comment]
cool :) just one more question: the automated build on dockerhub doesn't seem to work any more .. it's written there: "last pushed: a year ago".
Could you maybe fix this pipeline, too, so that the newest version can be loaded from dockerhub officially?

**Comment by kern** [comment]
@JannikZed you can find the automated builds at `dsys/match` now :)

https://hub.docker.com/r/dsys/match/
