### ISSUE TITLE
Trying out match

### ISSUE THREAD

**Issue by freeatnet** [pavlovml/match#3]
I'm having trouble trying out match.

I've started an ES instance:

```
docker run -d --name image-match-es elasticsearch
```

and a match instance:

```
docker run -e ELASTICSEARCH_URL=image-match-es --name image-match-server --link image-match-es -P pavlov/match
```

When issuing a `GET /ping`, I get a `200 OK` response; however, when trying to do anything else (`GET /list`, `POST /add`), I get a `500` with the following JSON response:

```
{"status": "fail", "result": [], "method": "", "error": ["TransportError(404, u'index_not_found_exception', u'no such index')"]}
```

I guess there's an ES index creation step I'm missing, but I can't find it after looking through the docs or the code. Could you advise on what needs to be done?

**Comment by jalliance** [comment]
+1

**Comment by freeatnet** [comment]
The solution appears to be to create an `images` index manually, as documented in https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html

It'd be cool if this was in the documentation!

**Comment by jalliance** [comment]
Did you manage to get it working? I tried creating the index manually, but apparently it already exists yet I still receive the same errors...

{"error":"IndexAlreadyExistsException[[images] already exists]","status":400}
