### ISSUE TITLE
make run not working

### ISSUE THREAD

**Issue by Catalin-Ionut** [pavlovml/match#30]
Hello,

I tried to use this package but i can't seem to make it work for the god of it.
I tried make run, make dev but always this same error.

Full log below. Does anyone know how to make it work?

https://pastebin.com/GyvTpZ3e

**Comment by phoenix-mstu** [comment]
i'm getting the same error

**Comment by phoenix-mstu** [comment]
I've fixed it. The project is not compatible to python 3.7, do i've just changed Dockerfile:

```
diff --git a/Dockerfile b/Dockerfile
index 814ee3f..ab41779 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM python:3
+FROM python:3.6
 MAINTAINER Alex Kern <alex@distributedsystems.com>
 
 RUN apt-get update && \
```

Also I run it on mac, and there was an issue with elasticsearch. There was an error:

`match_elasticsearch_1 exited with code 137`

I've fixed it by increasing memory limit for containers to 2.5Gb in docker settings.

Now container runs without issues.

**Comment by Joisar** [comment]
@phoenix-mstu Hello, I want to run this repository's code on server. Can you do it? It will be paid task. Thanks!
